Fetching vnet peering data
foreseeti/securicad-azure-collector pull request #5
Opened 2021-06-07 09:11 UTC by GlenGengforeseeti

Fetch the vnet peering data of the virtual networks. I think the name of the peering itself and the id of the remote network should be enough.

2021-06-08 05:49 UTC, Gyllingen commented on fetch_subscription_resources.py
> +                raw_vnetPeerings = raw_properties["virtualNetworkPeerings"]
raw_vnet_peerings

2021-06-08 05:50 UTC, Gyllingen commented on fetch_subscription_resources.py
> +                raw_vnetPeerings = raw_properties["virtualNetworkPeerings"]
and use .get["virtualNetworkPeerings, list())
It's something I've started using, in case the field returns None, you will instead get an empty list and your for loop below won't have any problems. Either that or use .get("virtualNetworkPeerings") and a or [] in your for loop

2021-06-08 05:52 UTC, Gyllingen commented on fetch_subscription_resources.py
> +                        "remote_network": raw_vnetPeering["properties"]["remoteVirtualNetwork"]["id"]
can we use .get() for these as well?

And for the last one you could do
raw_vnetPeering.get("properties", {}).get("remoteVirtualNetwork", {}).get("id") 

Then we should never get any issues here

2021-06-08 05:52 UTC, Gyllingen requested changes
small changes

2021-06-08 13:06 UTC, GlenGengforeseeti commented on fetch_subscription_resources.py
> +                raw_vnetPeerings = raw_properties["virtualNetworkPeerings"]
Solved

2021-06-09 06:07 UTC, Gyllingen approved these changes
LGTM

2021-06-09 06:21 UTC, merged